### ISSUE TITLE
List all empty database tables

### ISSUE THREAD

**Issue by eprogramming** [EsmerilProgramming/dev-utility-belt#14]
Useful for further investigation of unused tables and/or pieces of code related to these tables.

**Comment by danielsoro** [comment]
Nice! :)

**Comment by htmfilho** [comment]
Which database should we support first?

**Comment by eprogramming** [comment]
mariadb

**Comment by htmfilho** [comment]
Ok. This is the one already in the list of dependencies. Consider it done! (in a few days)

**Comment by htmfilho** [comment]
How to use it: https://github.com/EsmerilProgramming/dev-utility-belt/wiki/Functionalities#database
