### ISSUE TITLE
Use an in-memory database instead of mysql by default

### ISSUE THREAD

**Issue by htmfilho** [EsmerilProgramming/dev-utility-belt#16]
The support for MySQL remains, but it should be chosen explicitly.

**Comment by htmfilho** [comment]
@eprogramming, I've embedded SQLite into dev-utility-belt. Can you destroy the database jub in MySQL and test again the function (empty-tables) ? Thanks in advance.

**Comment by eprogramming** [comment]
@htmfilho ok

**Comment by eprogramming** [comment]
@htmfilho working fine +1
https://asciinema.org/a/18956
