### ISSUE TITLE
how i see log files of wildfly ?

### ISSUE THREAD

**Issue by eprogramming** [EsmerilProgramming/dev-utility-belt#20]
I tried but nothing appears, maybe I'm doing something wrong.

**Comment by htmfilho** [comment]
Issue #6 is still open. Address issue #20 when #6 is closed.

**Comment by htmfilho** [comment]
I will need this feature finished soon to help at work. I will work on it and I count on you to test it from your side. Please, follow up.

**Comment by eprogramming** [comment]
ok

**Comment by htmfilho** [comment]
To read the log file:

    (log-records "/opt/jboss/wildfly-8.2.0.Final/standalone/log/server.log")

To record the log file in the embedded database:

    (persist-log-records "/opt/jboss/wildfly-8.2.0.Final/standalone/log/server.log")
